### PR TITLE
Feature GitHub actions 

### PR DESCRIPTION
**Pull request by cric96**
Move current CI system from Travis to GitHub actions #57.
- [x] Build and test ScaFi with Gradle and Sbt 
- [ ] Publish artifacts (both for jvm and js). **Deferred** to when we solve https://github.com/scafi/scafi/issues/27

### CODE REVIEW

**Review by metaphori — APPROVED** [review]

**Comment by metaphori** [comment]
@cric96 We may also split this and defer the part about the publishing of artifacts to a later PR

**Comment by cric96** [comment]
Good idea @metaphori. Do we want to remove Gradle support from the CI already? Or do we move that work to a later PR?

**Comment by metaphori** [comment]
This could also be done in a later PR, logically, since this one is about GHA support.

**Pull request merged**
