### PR TITLE
Introduction of scala-js plugin support

### PR DESCRIPTION
**Pull request by cric96**
This work allow to trascompile ScaFi simulation and interpreter in javascript.
In https://scafijs.web.app/ there is the result of trascompilation of the file it.unibo.scafijs.Index stored in the project _scafijs_.

To trascompile in javascript follow this steps:

- open an sbt console
- type **project scafijs**
- type **fastOptJS**

To see the result, open scafijs/target/scafi-2.12/classes/index.html

This work will be considered with a view to future project.

### CODE REVIEW

**Comment by metaphori** [comment]
@cric96 I've merged, but I do have a doubt: does `enablePlugins(ScalaJSPlugin)` change the nature of the project (i.e., ScalaJS-only)? Because to support both platform (JS and JVM) there should be the need for [cross building](https://www.scala-js.org/doc/project/cross-build.html). What do you think?

**Comment by cric96** [comment]
You are right... At the beginning, when I altered the ScaFi build.sbt, I 
didn't want to alter the current directory structure so I didn't use the 
cross project. However, after some test, I've noticed that the 
compilation output contained .class too and the project started on JVM 
without any problems.
But, after your suggestions, I read more carefully the documentation. In 
https://www.scala-js.org/doc/project/building.html I found this phrase:
*Do not use these .class files to run your project on a JVM*
this means that enablePlugins(ScalaJSPlugin) change the nature of the 
project in some way, with the result of producing different .class.
Definitely, to use Scala.JS we have to use cross-building.
This leads to:

    1. change all projects that can be compiled on both platforms (e.g
    core, commons,..). Following the guide and the link
    https://github.com/portable-scala/sbt-crossproject, the core
    subproject configuration became:

    lazy val core = crossProject(JSPlatform, JVMPlatform).
             withoutSuffixFor(JVMPlatform).
             ...

    Furthermore, each project that depends on the core, must define the
    platform too (e.g core.jvm or core.js).
    2. in the "cross" project, the folder structure has to follow the
    template explained in
    https://www.scala-js.org/doc/project/cross-build.html

I've tried to change the sbt to enable cross-project and it seems to 
work. Initially, IDEA had some troubles, but with a fully rebuild (Build 
-> Build project), I managed to solve them.
Do you think that this modification is allowed? In general, I think that 
is better to create a separate branch in which explore the 
cross-building support.
Excuse me for the inconvenience.


Il 10/04/2020 12:05, Roberto Casadei ha scritto:

**Comment by metaphori** [comment]
No problem, it's my fault I did not carefully review the all thing.
Anyway, I've also started to adjust the build. 
Now I cross compile it; check out `develop` in case.
This works out, and I also adjusted the Gradle build to handle the new layout of cross projects.
I still have some issues with the "web" module: it seems the plugin doesn't work very well, or I am missing something.

- I specify the main module initialiser, though importing the `-fastopt.js` file generated by `fastOptJS` does not work, even though I manage to access exported JS elements (I developed a small façade for ScaFi).
- I tried to import a NPM module and use `scalajs-bundler`, but the `-bundle.js` file generated by `fastOptJS::webpack` does not allow me to see exported entities (even when [trying this](https://scalacenter.github.io/scalajs-bundler/cookbook.html#several-entry-points))

**Comment by cric96** [comment]
@metaphori I think I've got a solution. There were two main problems:

1.  `scalaJSMainModuleInitializer`: if you use `scalaJSMainModuleInitializer`, you need also to mark this project as _runnable_ using `scalaJSUseMainModuleInitializer:= true`, otherwise the project is considered a library. Furthermore, the second argument of `mainMethod ` has to be a def marked with `@JSExport` (e.g. main).
2. lack of the support of scala.js to java.time: this problem is more subtle, but there is a solution. In general, if the project uses some java dependent libraries, it cannot be compiled in javascript. Luckily, some standard libraries have a corresponding version in scala.js (e.g java.lange.Thread). The library java.time has official support (https://github.com/scala-js/scala-js-java-time), but for now, some implementations are missing, among them the class `LocalDateTime`. The latter is used in the simulation package. I have tried to change `LocalDateTime `in `LocalTime `and it seems to works. This change can be a problem?

With these changes, the simulation starts and I can access to your facade.
If you want I can create a cleaner version and make another PR.
P.S. Just out of curiosity, there is some reason to make scafi-web cross-project? I think that it has an only javascript part, hasn't not?

**Comment by metaphori** [comment]
Thanks for you answer

- I did try 1) but it did not work until I read that it was necessary to specify `in Compile`
- thanks for investigating into the `LocalDateTime` issue; I'll think about changing the type
- yeah no need to have it as a cross-project; I probably switched it on while trying to fix plugin-related issues

**Pull request merged**
